title: Minerva Medical
description: A Medical Inventory App
google_analytics:
show_downloads: false
theme: jekyll-theme-modernist
github:
  is_project_page: true
  repository_url: https://github.com/minerva-medical
gems:
  - jekyll-mentions
