title: Minerva
description: A Medical Inventory App
google_analytics:
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/minerva-medical/minerva
gems:
  - jekyll-mentions
